version: '3'

services:
  card_game-nginx:
    container_name: card_game-nginx
    image: nginx:1.21-alpine
    restart: on-failure
    volumes:
      - './:/var/www/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "8081:80"
    depends_on:
      - card_game-php

  card_game-php:
    container_name: card_game-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - ./.env
    user: 1000:1000
    volumes:
      - ./:/var/www/app